@hostname = http://localhost:3000

### GET ALL CARS
GET {{hostname}}/cars HTTP/1.1

### GET CAR
GET {{hostname}}/cars/949eb314-a034-4bef-8e5f-5fd2f1e4284e HTTP/1.1

###
POST {{hostname}}/cars HTTP/1.1
content-type: application/json

{
    "brand": "Tesla",
    "model": "Model S"
}

###
PATCH {{hostname}}/cars/2 HTTP/1.1
content-type: application/json

{
    "brand": "Tesla",
    "model": "Model S"
}

###
DELETE {{hostname}}/cars/2 HTTP/1.1
content-type: application/json